export enum Titulos {
  listaClientes = 'Lista de Clientes',
  cadastroCliente = 'Cadastro de Cliente',
  editarcliente = 'Editar Cliente',
  detalheCliente = 'Detalhe do Cliente',
  listaEmpresas = 'Lista de Empresas',
  cadastroEmpresa = 'Cadastro de Empresa',
  editarEmpresa = 'Editar Empresa',
  detalheEmpresa = 'Detalhe da Empresa',
  listaFornecedores = 'Lista de Fornecedores',
  cadastroFornecedor = 'Cadastro de Fornecedor',
  editarFornecedor = 'Editar Fornecedor',
  detalheFornecedor = 'Detalhe do Fornecedor',
  listaFuncionarios = 'Lista de Funcionarios',
  cadastroFuncionario = 'Cadastro de Funcionario',
  editarFuncionario = 'Editar Funcionario',
  detalheFuncionario = 'Detalhe do Funcionario',
  listaTransportadores = 'Lista de Transportadores',
  cadastroTransportador = 'Cadastro de Transportador',
  editarTransportador = 'Editar Transportador',
  detalheTransportador = 'Detalhe do Transportador',
  listaUsuarios = 'Lista de Usuarios',
  cadastroUsuario = 'Cadastro de Usuario',
  permissaoUsuario = 'Permissões do Usuario',
  editarUsuario = 'Editar Usuario',
  detalheUsuario = 'Detalhe do Usuario',
  selecionarFuncionario = 'Selecionar Funcionário',
}
